# -*- coding: utf-8 -*-
"""Concibido, Melrose

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19uBZ2cOsLgO_WVFm-LMJVYmq3pG60jvt

# My First R **Program**

# 1. Print
"""

print ("Hello World")

"""# 2. String Variable"""

myString <- ("Hello World")
print (myString)

myString <- "Hello World"
num <- 10
floatingNum <- 9.5
isBool <- TRUE

class(myString)
class(num)
class(floatingNum)
class(isBool)

"""# 5. Numerical Operators"""

x <- 5
y <- 3

sum <- x + y
sub <- x - y
mul <- x * y
div <- x / y
exp <- x ^ y


print(sum)
print(sub)
print(mul)
print(div)
print(exp)

cat("+", sum)
cat("-", sub)
cat("*", mul)
cat("/", div)

"""# 6. User Input"""

name <- readline("Enter Name ")
print(paste("Name:", name))

"""# 7. Decision Making"""

grade <- 80

if(grade <75) {
  print ("Failed")
}else{
  print ("Passed")
}

"""# 8. Loop"""

for(i in 1:5){
  print(i)
}

"""# 9. Functions"""

addNumber <- function (a,b){
  return (a+b)
}

addNumber(5,3)

"""# 10. Vectors"""

grades <- c(90,88,96,83,91)

grades

cat("MEAN:",mean(grades))
cat("\nMAX:",max(grades))
cat("\nMIN:",min(grades))
cat("\nSUM:",sum(grades))
cat("\nLENGTH:",length(grades))

"""# 11. Matrix"""

A <- matrix(c(1,2,3,4,5,6,7),nrow=2)
A

"""# 10. Lists"""

student <- list(
  Name="John",
  Age=20,
  GPA=1.5
)
 student

"""# 11. Data frames"""

students <- data.frame(
  Name=c("John", "Mary", "Anna"),
  Age=c(20,21,19),
  GPA=c(1.5,1.8,1.4)
)

students

write.csv(students,"student.csv")

"""# 12. Reading csv Files"""

data <- read.csv("student.csv")

head(data)

summary(data)